import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { RANGER_PARTS, SLIME_PARTS } from "../src/skeletal-assets.js";

const projectDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = path.join(projectDir, "src");
const outputPath = path.join(projectDir, "wechat", "game.js");
const generatedAssetsDir = path.join(projectDir, "assets", "generated");
const generatedAssetsOutput = path.join(projectDir, "wechat", "assets", "generated");
const modules = ["core", "skeletal-assets", "renderer", "puzzle-core", "puzzle-renderer", "puzzle-runtime", "platform-wechat", "main-wechat"];

function compileModule(id) {
  const filePath = path.join(srcDir, `${id}.js`);
  let source = fs.readFileSync(filePath, "utf8");
  const exported = new Set();

  source = source.replace(
    /import\s*{([\s\S]*?)}\s*from\s*["']\.\/([^"']+)["'];?/g,
    (_match, names, dependency) => {
      const dependencyId = dependency.replace(/\.js$/, "");
      return `const {${names}} = __require(${JSON.stringify(dependencyId)});`;
    },
  );

  source = source.replace(/\bexport\s+(const|class|function)\s+([A-Za-z_$][\w$]*)/g, (_match, kind, name) => {
    exported.add(name);
    return `${kind} ${name}`;
  });

  source = source.replace(/\bexport\s*{([^}]+)}\s*;?/g, (_match, list) => {
    for (const entry of list.split(",")) {
      const [local] = entry.trim().split(/\s+as\s+/);
      if (local) exported.add(local);
    }
    return "";
  });

  const assignment = exported.size
    ? `\nObject.assign(exports, { ${[...exported].join(", ")} });`
    : "";
  return `__define(${JSON.stringify(id)}, function (exports, __require) {\n${source}${assignment}\n});`;
}

const runtime = `"use strict";
// Generated by scripts/build-wechat.mjs. Edit src/*, then rebuild.
const __factories = Object.create(null);
const __cache = Object.create(null);
function __define(id, factory) { __factories[id] = factory; }
function __require(id) {
  if (__cache[id]) return __cache[id].exports;
  const factory = __factories[id];
  if (!factory) throw new Error("Unknown bundled module: " + id);
  const module = { exports: {} };
  __cache[id] = module;
  factory(module.exports, __require);
  return module.exports;
}
`;

const bundle = `${runtime}\n${modules.map(compileModule).join("\n\n")}\n\n__require("main-wechat");\n`;
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, bundle, "utf8");
fs.rmSync(generatedAssetsOutput, { recursive: true, force: true });
fs.mkdirSync(generatedAssetsOutput, { recursive: true });
fs.copyFileSync(
  path.join(generatedAssetsDir, "battlefield-anime-v2.png"),
  path.join(generatedAssetsOutput, "battlefield-anime-v2.png"),
);
for (const [group, parts] of [["ranger", RANGER_PARTS], ["slime", SLIME_PARTS]]) {
  const sourceParts = path.join(generatedAssetsDir, group, "parts");
  const outputParts = path.join(generatedAssetsOutput, group, "parts");
  fs.mkdirSync(outputParts, { recursive: true });
  for (const part of parts) {
    const filename = `${part}.png`;
    fs.copyFileSync(path.join(sourceParts, filename), path.join(outputParts, filename));
  }
}
fs.mkdirSync(path.join(generatedAssetsOutput, "puzzle"), { recursive: true });
fs.copyFileSync(path.join(generatedAssetsDir, "puzzle", "heroine-portraits-v1.png"), path.join(generatedAssetsOutput, "puzzle", "heroine-portraits-v1.png"));
console.log(`Built ${path.relative(projectDir, outputPath)} (${Buffer.byteLength(bundle)} bytes)`);
console.log("Copied puzzle portraits, battlefield and skeletal parts (source rig atlases excluded)");
