"use strict";
// Generated by scripts/build-wechat.mjs. Edit src/*, then rebuild.
const __factories = Object.create(null);
const __cache = Object.create(null);
function __define(id, factory) { __factories[id] = factory; }
function __require(id) {
  if (__cache[id]) return __cache[id].exports;
  const factory = __factories[id];
  if (!factory) throw new Error("Unknown bundled module: " + id);
  const module = { exports: {} };
  __cache[id] = module;
  factory(module.exports, __require);
  return module.exports;
}

__define("core", function (exports, __require) {
const LOGICAL_WIDTH = 1280;
const LOGICAL_HEIGHT = 720;

const BOARD = Object.freeze({
  x: 76,
  y: 88,
  width: 1128,
  height: 456,
  rows: 5,
  cols: 9,
  playerCols: 7,
});

const UI = Object.freeze({
  cardsX: 28,
  cardsY: 594,
  cardWidth: 96,
  cardHeight: 108,
  cardGap: 6,
  readyStart: { x: 561, y: 286, w: 158, h: 56 },
  controls: [
    { id: "start", label: "开始", x: 908, y: 18, w: 68, h: 38 },
    { id: "pause", label: "暂停", x: 982, y: 18, w: 68, h: 38 },
    { id: "restart", label: "重开", x: 1056, y: 18, w: 68, h: 38 },
    { id: "save", label: "存档", x: 1130, y: 18, w: 68, h: 38 },
  ],
});

const ELEMENT_ORDER = ["fire", "ice", "lightning", "nature"];

const ELEMENTS = Object.freeze({
  fire: { id: "fire", name: "火", color: "#ff765f", glyph: "火" },
  ice: { id: "ice", name: "冰", color: "#6bd9ff", glyph: "冰" },
  lightning: { id: "lightning", name: "雷", color: "#ffe36a", glyph: "雷" },
  nature: { id: "nature", name: "自然", color: "#75e49d", glyph: "木" },
});

const ROLE_DEFS = Object.freeze({
  ranger: {
    id: "ranger", name: "游侠", glyph: "弓", color: "#e86955", cost: 8, cooldown: 4,
    hp: 330, attack: 36, interval: 0.82, range: 620, speed: 54, armor: 0.03,
  },
  captain: {
    id: "captain", name: "队长", glyph: "盾", color: "#5e91d7", cost: 10, cooldown: 6, block: 3,
    hp: 940, attack: 44, interval: 1.08, range: 72, speed: 42, armor: 0.16,
  },
  alchemist: {
    id: "alchemist", name: "炼金", glyph: "瓶", color: "#d785d7", cost: 9, cooldown: 5,
    hp: 440, attack: 50, interval: 1.35, range: 500, speed: 45, armor: 0.05, splash: 52,
  },
  mage: {
    id: "mage", name: "术士", glyph: "法", color: "#8b75df", cost: 12, cooldown: 7,
    hp: 390, attack: 73, interval: 1.58, range: 620, speed: 43, armor: 0.02, splash: 66,
  },
  engineer: {
    id: "engineer", name: "工匠", glyph: "机", color: "#d89a49", cost: 9, cooldown: 5,
    hp: 510, attack: 39, interval: 0.72, range: 500, speed: 47, armor: 0.08,
  },
  priest: {
    id: "priest", name: "祭司", glyph: "祷", color: "#65c9bb", cost: 10, cooldown: 6,
    hp: 450, attack: 29, interval: 1.18, range: 500, speed: 44, armor: 0.04,
    heal: 58, healInterval: 1.65, healRange: 500,
  },
  golem: {
    id: "golem", name: "石卫", glyph: "岩", color: "#8c96a3", cost: 12, cooldown: 8,
    hp: 1240, attack: 56, interval: 1.42, range: 72, speed: 31, armor: 0.22,
  },
  wolf: {
    id: "wolf", name: "林狼", glyph: "狼", color: "#70aa69", cost: 8, cooldown: 3.5,
    hp: 410, attack: 42, interval: 0.62, range: 72, speed: 76, armor: 0.04,
  },
});

const MONSTER_DEFS = Object.freeze({
  slime: {
    id: "slime", name: "角团", glyph: "团", color: "#9b74d7",
    hp: 320, attack: 50, interval: 1 / 0.75, range: 48, speed: 56, armor: 0, bounty: 1, gateDamage: 1,
  },
  bat: {
    id: "bat", name: "夜翼", glyph: "翼", color: "#6571b4",
    hp: 380, attack: 55, interval: 0.78, range: 50, speed: 69, armor: 0.02, bounty: 1, gateDamage: 1,
  },
  mushroom: {
    id: "mushroom", name: "孢子", glyph: "菇", color: "#d2608c",
    hp: 460, attack: 60, interval: 1 / 0.55, range: 376, speed: 38, armor: 0, bounty: 1, gateDamage: 1,
  },
  brute: {
    id: "brute", name: "石兽", glyph: "兽", color: "#9b785f",
    hp: 1800, attack: 125, interval: 1 / 0.45, range: 58, speed: 23, armor: 0.25, bounty: 4, gateDamage: 2,
  },
  boss: {
    id: "boss", name: "荒角王", glyph: "王", color: "#c04e66",
    hp: 8000, attack: 180, interval: 1 / 0.6, range: 72, speed: 18, armor: 0.15, bounty: 15, gateDamage: 5,
  },
});

const ROLE_CARDS = Object.values(ROLE_DEFS).map((role) => ({
  id: `role:${role.id}`,
  type: "role",
  payloadId: role.id,
  name: role.name,
  glyph: role.glyph,
  color: role.color,
  cost: role.cost,
  cooldown: role.cooldown,
}));

const ENERGY_CARDS = ELEMENT_ORDER.map((id) => ({
  id: `energy:${id}`,
  type: "energy",
  payloadId: id,
  name: ELEMENTS[id].name,
  glyph: ELEMENTS[id].glyph,
  color: ELEMENTS[id].color,
  cost: 4,
  cooldown: 6,
}));

const CARD_DEFS = Object.freeze([...ROLE_CARDS, ...ENERGY_CARDS]);

const FORM_RECIPES = Object.freeze({
  "fire+fire": {
    name: "炽焰", hp: 1.05, attack: 1.42, rate: 1.08,
    traits: { burn: 0.34, splash: 42 }, colors: ["#ff5f4a", "#ffbc63"],
  },
  "ice+ice": {
    name: "极霜", hp: 1.28, attack: 1.12, rate: 0.95, armor: 0.14,
    traits: { slow: 0.42 }, colors: ["#5acaff", "#d9f7ff"],
  },
  "lightning+lightning": {
    name: "鸣雷", hp: 1.06, attack: 1.16, rate: 1.42,
    traits: { chain: 2 }, colors: ["#ffe76a", "#fff7c3"],
  },
  "nature+nature": {
    name: "森灵", hp: 1.52, attack: 1.08, rate: 1.02, armor: 0.06,
    traits: { regen: 0.018 }, colors: ["#55dc8a", "#c5f48d"],
  },
  "fire+ice": {
    name: "雾爆", hp: 1.16, attack: 1.28, rate: 1.1,
    traits: { slow: 0.22, splash: 64, knockback: 18 }, colors: ["#ff8063", "#75dcff"],
  },
  "fire+lightning": {
    name: "过载", hp: 1.05, attack: 1.36, rate: 1.25,
    traits: { burn: 0.2, chain: 1, splash: 38 }, colors: ["#ff6d58", "#ffe468"],
  },
  "fire+nature": {
    name: "燃芽", hp: 1.28, attack: 1.24, rate: 1.08,
    traits: { burn: 0.2, lifesteal: 0.18, regen: 0.006 }, colors: ["#ff755c", "#69df91"],
  },
  "ice+lightning": {
    name: "霜闪", hp: 1.12, attack: 1.2, rate: 1.28,
    traits: { slow: 0.28, chain: 1 }, colors: ["#66d8ff", "#ffe77a"],
  },
  "ice+nature": {
    name: "霜林", hp: 1.4, attack: 1.1, rate: 1.03, armor: 0.08,
    traits: { slow: 0.26, regen: 0.012 }, colors: ["#72dfff", "#65df91"],
  },
  "lightning+nature": {
    name: "生息", hp: 1.24, attack: 1.14, rate: 1.32,
    traits: { chain: 1, healPulse: 0.1 }, colors: ["#ffe46c", "#6ce29a"],
  },
});

const WAVE_POINTS = Object.freeze([20, 24, 28, 32, 36, 42]);
const WAVE_DURATION = 35;

const WAVE_SPECS = Object.freeze([
  [
    [0.0, "slime", 1], [3.0, "slime", 3], [6.0, "slime", 1],
    [9.0, "slime", 3], [12.0, "slime", 1], [15.0, "slime", 3],
  ],
  [
    [0.0, "slime", 0], [2.0, "bat", 4], [4.0, "slime", 2], [6.0, "bat", 1],
    [8.0, "slime", 3], [10.5, "bat", 0], [13.0, "mushroom", 2], [16.0, "slime", 4],
  ],
  [
    [0.0, "slime", 1], [1.8, "bat", 4], [3.6, "slime", 2], [5.4, "bat", 0],
    [7.4, "mushroom", 3], [9.5, "slime", 0], [11.7, "slime", 4], [14.0, "brute", 2],
    [17.0, "mushroom", 1],
  ],
  [
    [0.0, "brute", 2], [1.7, "slime", 4], [3.4, "mushroom", 0], [5.1, "bat", 3],
    [6.8, "slime", 1], [8.5, "mushroom", 4], [10.2, "bat", 0], [12.0, "mushroom", 2],
    [14.2, "mushroom", 1], [17.0, "brute", 3],
  ],
  [
    [0.0, "brute", 0], [1.6, "brute", 4], [3.2, "mushroom", 1], [4.8, "mushroom", 3],
    [6.4, "bat", 0], [8.0, "bat", 4], [9.6, "slime", 1], [11.2, "slime", 2],
    [12.8, "mushroom", 0], [14.4, "mushroom", 4], [17.0, "brute", 2],
  ],
  [
    [0.0, "boss", 2], [1.8, "bat", 0], [3.6, "bat", 4], [5.4, "mushroom", 1],
    [7.2, "mushroom", 3], [9.0, "brute", 0], [11.0, "brute", 4], [13.0, "bat", 1],
    [15.0, "bat", 3], [17.0, "mushroom", 2], [20.0, "brute", 2],
  ],
]);

const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
const inRect = (x, y, rect) => x >= rect.x && x <= rect.x + rect.w && y >= rect.y && y <= rect.y + rect.h;

function sortedElements(elements) {
  return [...elements].sort((a, b) => ELEMENT_ORDER.indexOf(a) - ELEMENT_ORDER.indexOf(b)).join("+");
}

function cellCenter(row, col) {
  const cellW = BOARD.width / BOARD.cols;
  const cellH = BOARD.height / BOARD.rows;
  return {
    x: BOARD.x + cellW * (col + 0.5),
    y: BOARD.y + cellH * (row + 0.5),
  };
}

function pointToCell(x, y) {
  if (!inRect(x, y, { x: BOARD.x, y: BOARD.y, w: BOARD.width, h: BOARD.height })) return null;
  return {
    row: clamp(Math.floor((y - BOARD.y) / (BOARD.height / BOARD.rows)), 0, BOARD.rows - 1),
    col: clamp(Math.floor((x - BOARD.x) / (BOARD.width / BOARD.cols)), 0, BOARD.cols - 1),
  };
}

function cardRect(index) {
  return {
    x: UI.cardsX + index * (UI.cardWidth + UI.cardGap),
    y: UI.cardsY,
    w: UI.cardWidth,
    h: UI.cardHeight,
  };
}

function freshState(seed = 0x51a7c3) {
  return {
    schemaVersion: 2,
    phase: "ready",
    previousPhase: "ready",
    battleTime: 0,
    resource: 20,
    resourceMax: 99,
    resourceClock: 0,
    gateHp: 10,
    gateMaxHp: 10,
    deck: CARD_DEFS.map((card) => ({ cardId: card.id, cooldownLeft: 0, flash: 0 })),
    selectedCardId: null,
    units: [],
    enemies: [],
    effects: [],
    wave: { index: -1, elapsed: 0, duration: WAVE_DURATION, nextSpawnIndex: 0, intermission: 0 },
    rngSeed: seed >>> 0,
    nextEntityId: 1,
    message: null,
    messageTtl: 0,
  };
}

class TowerDefenseGame {
  constructor(seed) {
    this.state = freshState(seed);
  }

  reset(seed = this.state.rngSeed || 0x51a7c3) {
    this.state = freshState(seed);
  }

  random() {
    let x = this.state.rngSeed || 1;
    x ^= x << 13;
    x ^= x >>> 17;
    x ^= x << 5;
    this.state.rngSeed = x >>> 0;
    return this.state.rngSeed / 4294967296;
  }

  begin() {
    const { state } = this;
    if (state.phase === "paused") {
      state.phase = state.previousPhase === "paused" ? "playing" : state.previousPhase;
      return;
    }
    if (state.phase === "ready") this.startWave(0);
  }

  togglePause() {
    const { state } = this;
    if (["victory", "defeat", "ready"].includes(state.phase)) return;
    if (state.phase === "paused") {
      state.phase = state.previousPhase;
    } else {
      state.previousPhase = state.phase;
      state.phase = "paused";
    }
  }

  pauseForVisibility() {
    if (!["paused", "ready", "victory", "defeat"].includes(this.state.phase)) this.togglePause();
  }

  startWave(index) {
    const state = this.state;
    state.wave.index = index;
    state.wave.elapsed = 0;
    state.wave.nextSpawnIndex = 0;
    state.wave.intermission = 0;
    state.wave.duration = WAVE_DURATION;
    if (index > 0) state.resource = Math.min(state.resourceMax, Math.max(state.resource, WAVE_POINTS[index]));
    state.phase = "playing";
    state.units.forEach((unit) => {
      unit.hp = Math.min(unit.maxHp, unit.hp + unit.maxHp * 0.24);
      unit.targetId = null;
    });
    this.addEffect({ type: "banner", text: `${index + 1} / ${WAVE_SPECS.length}`, ttl: 1.2 });
  }

  update(dt) {
    const state = this.state;
    dt = clamp(dt, 0, 0.05);
    this.updateUiTimers(dt);
    if (!['playing', 'intermission'].includes(state.phase)) return;

    state.battleTime += dt;
    state.resourceClock += dt;
    while (state.resourceClock >= 3) {
      state.resourceClock -= 3;
      state.resource = Math.min(state.resourceMax, state.resource + 1);
    }
    state.deck.forEach((slot) => { slot.cooldownLeft = Math.max(0, slot.cooldownLeft - dt); });

    if (state.phase === "intermission") {
      state.wave.intermission -= dt;
      this.updateStatuses(dt);
      if (state.wave.intermission <= 0) this.startWave(state.wave.index + 1);
      return;
    }

    this.updateSpawns(dt);
    this.updateStatuses(dt);
    this.updateActors(dt);
    this.cleanupActors();
    this.checkWaveEnd();
  }

  updateUiTimers(dt) {
    const state = this.state;
    state.deck.forEach((slot) => { slot.flash = Math.max(0, slot.flash - dt); });
    state.messageTtl = Math.max(0, state.messageTtl - dt);
    if (state.messageTtl === 0) state.message = null;
    state.effects.forEach((effect) => { effect.ttl -= dt; });
    state.effects = state.effects.filter((effect) => effect.ttl > 0);
  }

  updateSpawns(dt) {
    const state = this.state;
    const spec = WAVE_SPECS[state.wave.index];
    state.wave.elapsed += dt;
    while (state.wave.nextSpawnIndex < spec.length && spec[state.wave.nextSpawnIndex][0] <= state.wave.elapsed) {
      const [, type, row] = spec[state.wave.nextSpawnIndex];
      this.spawnMonster(type, row, state.wave.index);
      state.wave.nextSpawnIndex += 1;
    }
  }

  spawnMonster(type, row, waveIndex) {
    const def = MONSTER_DEFS[type];
    const scaleHp = type === "boss" ? 1 : 1 + waveIndex * 0.1;
    const scaleAttack = type === "boss" ? 1 : 1 + waveIndex * 0.07;
    const lane = clamp(row, 0, BOARD.rows - 1);
    const spawnCol = BOARD.cols - 1;
    const at = cellCenter(lane, spawnCol);
    const entity = {
      id: `e${this.state.nextEntityId++}`,
      side: "enemy",
      monsterId: type,
      name: def.name,
      glyph: def.glyph,
      color: def.color,
      x: at.x,
      y: at.y,
      lane,
      cellCol: spawnCol,
      radius: type === "boss" ? 32 : type === "brute" ? 25 : 20,
      hp: Math.round(def.hp * scaleHp),
      maxHp: Math.round(def.hp * scaleHp),
      attack: Math.round(def.attack * scaleAttack),
      interval: def.interval,
      range: def.range,
      speed: def.speed,
      armor: def.armor,
      bounty: def.bounty,
      gateDamage: def.gateDamage,
      attackTimer: this.random() * 0.35,
      targetId: null,
      blockedById: null,
      statuses: {},
      hitFlash: 0,
    };
    this.state.enemies.push(entity);
    this.addEffect({ type: "spawn", x: entity.x, y: entity.y, color: entity.color, ttl: 0.45 });
  }

  updateStatuses(dt) {
    const actors = [...this.state.units, ...this.state.enemies];
    for (const actor of actors) {
      actor.hitFlash = Math.max(0, (actor.hitFlash || 0) - dt);
      const burn = actor.statuses?.burn;
      if (burn) {
        burn.ttl -= dt;
        actor.hp -= burn.dps * dt;
        if (burn.ttl <= 0) delete actor.statuses.burn;
      }
      const slow = actor.statuses?.slow;
      if (slow) {
        slow.ttl -= dt;
        if (slow.ttl <= 0) delete actor.statuses.slow;
      }
      if (actor.side === "ally" && actor.traits?.regen && actor.hp > 0) {
        actor.hp = Math.min(actor.maxHp, actor.hp + actor.maxHp * actor.traits.regen * dt);
      }
    }
  }

  updateActors(dt) {
    // Defenders never move: they only acquire enemies in their own lane and in range.
    for (const unit of this.state.units) {
      if (unit.hp <= 0) continue;
      unit.attackTimer = Math.max(0, unit.attackTimer - dt);
      if (unit.roleId === "priest" && this.tryHeal(unit)) continue;

      let target = this.state.enemies.find((enemy) =>
        enemy.id === unit.targetId && this.isDefenderTargetValid(unit, enemy));
      if (!target) {
        target = this.findLaneEnemy(unit);
        unit.targetId = target?.id || null;
      }
      if (target && unit.attackTimer <= 0) {
        unit.attackTimer += unit.interval;
        this.performAttack(unit, target);
      }
    }

    // Attack intent and physical blocking are separate: ranged attackers never
    // reserve a defender's block slot merely by choosing it as a target.
    for (const enemy of this.state.enemies) {
      if (enemy.hp <= 0) continue;
      enemy.attackTimer = Math.max(0, enemy.attackTimer - dt);
      enemy.y = cellCenter(enemy.lane, 0).y;

      let target = this.state.units.find((unit) =>
        unit.id === enemy.blockedById && this.isPhysicalBlock(enemy, unit));
      if (!target) enemy.blockedById = null;

      target ||= this.state.units.find((unit) =>
        unit.id === enemy.targetId && this.isDefenderAhead(enemy, unit));
      if (!target) {
        target = this.findLaneDefender(enemy);
        enemy.targetId = target?.id || null;
      }
      if (!target) {
        this.moveEnemyToGate(enemy, dt);
        continue;
      }

      const attackDistance = enemy.range + target.radius * 0.45;
      const gap = enemy.x - target.x;
      const isRangedEnemy = enemy.range > BOARD.width / BOARD.cols * 1.5;
      if (gap > attackDistance + 0.01) {
        this.advanceEnemy(enemy, gap - attackDistance, dt);
      } else if (isRangedEnemy) {
        enemy.blockedById = null;
        if (enemy.attackTimer <= 0) {
          enemy.attackTimer += enemy.interval;
          this.performAttack(enemy, target);
        }
      } else if (this.hasBlockSlot(enemy, target)) {
        enemy.blockedById = target.id;
        enemy.targetId = target.id;
        if (enemy.attackTimer <= 0) {
          enemy.attackTimer += enemy.interval;
          this.performAttack(enemy, target);
        }
      } else {
        enemy.targetId = null;
        const nextTarget = this.findLaneBlocker(enemy);
        if (!nextTarget) {
          this.moveEnemyToGate(enemy, dt);
          continue;
        }
        enemy.targetId = nextTarget.id;
        const nextGap = enemy.x - nextTarget.x;
        const nextDistance = enemy.range + nextTarget.radius * 0.45;
        if (nextGap > nextDistance + 0.01) {
          this.advanceEnemy(enemy, nextGap - nextDistance, dt);
        } else if (this.hasBlockSlot(enemy, nextTarget)) {
          enemy.blockedById = nextTarget.id;
          if (enemy.attackTimer <= 0) {
            enemy.attackTimer += enemy.interval;
            this.performAttack(enemy, nextTarget);
          }
        }
      }
    }
  }

  advanceEnemy(enemy, remainingDistance, dt) {
    const slowFactor = enemy.statuses?.slow ? 1 - enemy.statuses.slow.amount : 1;
    const step = Math.min(enemy.speed * slowFactor * dt, remainingDistance);
    enemy.x -= Math.max(0, step);
  }

  isDefenderAhead(enemy, unit) {
    return unit.hp > 0 && unit.lane === enemy.lane && unit.x <= enemy.x + unit.radius;
  }

  findLaneDefender(enemy) {
    return this.state.units
      .filter((unit) => this.isDefenderAhead(enemy, unit))
      .sort((a, b) => b.x - a.x || a.id.localeCompare(b.id))[0] || null;
  }

  hasBlockSlot(enemy, unit) {
    const claimed = this.state.enemies.filter((other) =>
      other.hp > 0 && other.id !== enemy.id && other.blockedById === unit.id).length;
    return claimed < (unit.blockCapacity || 1);
  }

  isPhysicalBlock(enemy, unit) {
    if (!this.isDefenderAhead(enemy, unit) || !this.hasBlockSlot(enemy, unit)) return false;
    const contactDistance = enemy.range + unit.radius * 0.45;
    return enemy.x - unit.x <= contactDistance + 0.01;
  }

  findLaneBlocker(enemy) {
    return this.state.units
      .filter((unit) => this.isDefenderAhead(enemy, unit) && this.hasBlockSlot(enemy, unit))
      .sort((a, b) => b.x - a.x || a.id.localeCompare(b.id))[0] || null;
  }

  isDefenderTargetValid(unit, enemy) {
    const forwardDistance = enemy.x - unit.x;
    return enemy.hp > 0 && enemy.lane === unit.lane && forwardDistance >= -8 &&
      forwardDistance <= unit.range + enemy.radius * 0.45;
  }

  findLaneEnemy(unit) {
    return this.state.enemies
      .filter((enemy) => this.isDefenderTargetValid(unit, enemy))
      .sort((a, b) => a.x - b.x || a.id.localeCompare(b.id))[0] || null;
  }


  tryHeal(priest) {
    if (priest.attackTimer > 0) return false;
    const wounded = this.state.units
      .filter((unit) => unit.hp > 0 && unit.hp < unit.maxHp * 0.88 && distance(priest, unit) <= ROLE_DEFS.priest.healRange)
      .sort((a, b) => a.hp / a.maxHp - b.hp / b.maxHp)[0];
    if (!wounded) return false;
    const healAmount = Math.round(58 * (priest.attack / ROLE_DEFS.priest.attack));
    wounded.hp = Math.min(wounded.maxHp, wounded.hp + healAmount);
    priest.attackTimer = Math.max(priest.interval, ROLE_DEFS.priest.healInterval);
    this.addEffect({ type: "heal", fromX: priest.x, fromY: priest.y, x: wounded.x, y: wounded.y, ttl: 0.45 });
    return true;
  }

  moveEnemyToGate(enemy, dt) {
    const slowFactor = enemy.statuses?.slow ? 1 - enemy.statuses.slow.amount : 1;
    enemy.x -= enemy.speed * slowFactor * dt;
    if (enemy.x <= BOARD.x + 8) {
      this.state.gateHp = Math.max(0, this.state.gateHp - enemy.gateDamage);
      enemy.hp = 0;
      this.addEffect({ type: "gate", x: BOARD.x + 8, y: enemy.y, color: "#ff6677", ttl: 0.65 });
      if (this.state.gateHp <= 0) {
        this.state.phase = "defeat";
        this.state.selectedCardId = null;
      }
    }
  }

  performAttack(attacker, target) {
    const isRanged = attacker.range > 90;
    const attackPower = this.getAttackPower(attacker);
    this.damage(target, attackPower, attacker);
    this.addEffect({
      type: isRanged ? "shot" : "slash",
      fromX: attacker.x, fromY: attacker.y, x: target.x, y: target.y,
      color: attacker.formColors?.[0] || attacker.color, ttl: isRanged ? 0.22 : 0.16,
    });

    const traits = attacker.traits || {};
    if (traits.burn && target.hp > 0) {
      target.statuses.burn = { dps: attackPower * traits.burn, ttl: 3 };
    }
    if (traits.slow && target.hp > 0) {
      target.statuses.slow = { amount: traits.slow, ttl: 2.5 };
    }
    if (traits.knockback && target.hp > 0) {
      const direction = attacker.side === "ally" ? 1 : -1;
      target.x = clamp(target.x + direction * traits.knockback, BOARD.x + 8, BOARD.x + BOARD.width - 8);
    }

    const opponents = attacker.side === "ally" ? this.state.enemies : this.state.units;
    const splashRadius = Math.max(attacker.splash || 0, traits.splash || 0);
    if (splashRadius > 0) {
      opponents.forEach((other) => {
        if (other.id !== target.id && other.hp > 0 && this.isSecondaryTargetAllowed(attacker, other) &&
          distance(target, other) <= splashRadius) {
          this.damage(other, attackPower * 0.42, attacker, true);
        }
      });
      this.addEffect({ type: "burst", x: target.x, y: target.y, radius: splashRadius, color: attacker.color, ttl: 0.26 });
    }

    if (traits.chain) {
      const chainTargets = opponents
        .filter((other) => other.id !== target.id && other.hp > 0 &&
          this.isSecondaryTargetAllowed(attacker, other) && distance(target, other) <= 150)
        .sort((a, b) => distance(target, a) - distance(target, b))
        .slice(0, traits.chain);
      let previous = target;
      chainTargets.forEach((other, index) => {
        this.damage(other, attackPower * (0.46 - index * 0.08), attacker, true);
        this.addEffect({ type: "chain", fromX: previous.x, fromY: previous.y, x: other.x, y: other.y, ttl: 0.25 });
        previous = other;
      });
    }

    if (traits.lifesteal) attacker.hp = Math.min(attacker.maxHp, attacker.hp + attackPower * traits.lifesteal);
    if (traits.healPulse) {
      const allies = attacker.side === "ally" ? this.state.units : this.state.enemies;
      const ally = allies.filter((unit) => unit.hp > 0).sort((a, b) => a.hp / a.maxHp - b.hp / b.maxHp)[0];
      if (ally) {
        ally.hp = Math.min(ally.maxHp, ally.hp + attackPower * traits.healPulse);
        this.addEffect({ type: "heal", fromX: attacker.x, fromY: attacker.y, x: ally.x, y: ally.y, ttl: 0.28 });
      }
    }
  }

  getAttackPower(attacker) {
    if (attacker.side !== "enemy") return attacker.attack;
    const overtime = Math.max(0, this.state.wave.elapsed - WAVE_DURATION);
    return attacker.attack * (1 + overtime / 20);
  }

  isSecondaryTargetAllowed(attacker, target) {
    return attacker.side !== "ally" || target.x >= attacker.x - 8;
  }

  damage(target, rawDamage, source, secondary = false) {
    const damage = Math.max(1, rawDamage * (1 - clamp(target.armor || 0, 0, 0.72)));
    target.hp -= damage;
    target.hitFlash = 0.11;
    if (!secondary && damage >= 1) {
      this.addEffect({ type: "number", x: target.x, y: target.y - target.radius, value: Math.round(damage), color: "#ffffff", ttl: 0.55 });
    }
    if (target.hp <= 0) {
      target.hp = 0;
      source.targetId = null;
      if (source.blockedById === target.id) source.blockedById = null;
      this.addEffect({ type: "down", x: target.x, y: target.y, color: target.color, ttl: 0.5 });
    }
  }

  cleanupActors() {
    const deadEnemies = this.state.enemies.filter((enemy) => enemy.hp <= 0);
    deadEnemies.forEach((enemy) => {
      if (enemy.x > BOARD.x + 9) this.state.resource = Math.min(this.state.resourceMax, this.state.resource + enemy.bounty);
    });
    this.state.enemies = this.state.enemies.filter((enemy) => enemy.hp > 0);
    this.state.units = this.state.units.filter((unit) => unit.hp > 0);
  }

  checkWaveEnd() {
    if (this.state.phase !== "playing") return;
    const spec = WAVE_SPECS[this.state.wave.index];
    if (this.state.wave.nextSpawnIndex < spec.length || this.state.enemies.length > 0) return;
    if (this.state.wave.index === WAVE_SPECS.length - 1) {
      this.state.phase = "victory";
      this.state.selectedCardId = null;
      this.addEffect({ type: "banner", text: "完成", ttl: 3 });
    } else {
      this.state.phase = "intermission";
      this.state.wave.intermission = 3.5;
      this.addEffect({ type: "banner", text: `${WAVE_POINTS[this.state.wave.index + 1]}`, ttl: 1 });
    }
  }

  handleTap(x, y) {
    if (this.state.phase === "ready" && !this.state.selectedCardId && inRect(x, y, UI.readyStart)) {
      this.begin();
      return { type: "start" };
    }

    for (const button of UI.controls) {
      if (!inRect(x, y, button)) continue;
      if (button.id === "start") this.begin();
      if (button.id === "pause") this.togglePause();
      if (button.id === "restart") {
        this.reset();
        return { type: "restart" };
      }
      if (button.id === "save") return { type: "save" };
      return { type: button.id };
    }

    const cardIndex = CARD_DEFS.findIndex((_, index) => inRect(x, y, cardRect(index)));
    if (cardIndex >= 0) {
      const card = CARD_DEFS[cardIndex];
      this.state.selectedCardId = this.state.selectedCardId === card.id ? null : card.id;
      return { type: "select", cardId: this.state.selectedCardId };
    }

    const selected = CARD_DEFS.find((card) => card.id === this.state.selectedCardId);
    if (!selected || ["victory", "defeat", "paused"].includes(this.state.phase)) return null;
    if (selected.type === "role") return this.tryDeploy(selected, x, y);
    return this.tryApplyEnergy(selected, x, y);
  }

  tryDeploy(card, x, y) {
    const cell = pointToCell(x, y);
    if (!cell || cell.col >= BOARD.playerCols) return this.rejectCard(card.id);
    if (this.state.units.length >= 12) return this.rejectCard(card.id);
    const at = cellCenter(cell.row, cell.col);
    if (this.state.units.some((unit) => unit.lane === cell.row && unit.cellCol === cell.col)) return this.rejectCard(card.id);
    const slot = this.state.deck.find((item) => item.cardId === card.id);
    if (this.state.resource < card.cost || slot.cooldownLeft > 0) return this.rejectCard(card.id);

    this.state.resource -= card.cost;
    slot.cooldownLeft = card.cooldown;
    const def = ROLE_DEFS[card.payloadId];
    this.state.units.push({
      id: `u${this.state.nextEntityId++}`,
      side: "ally",
      roleId: def.id,
      name: def.name,
      glyph: def.glyph,
      color: def.color,
      x: at.x,
      y: at.y,
      lane: cell.row,
      cellCol: cell.col,
      radius: def.id === "golem" ? 26 : def.id === "wolf" ? 19 : 22,
      hp: def.hp,
      maxHp: def.hp,
      attack: def.attack,
      interval: def.interval,
      range: def.range,
      speed: def.speed,
      armor: def.armor,
      splash: def.splash || 0,
      blockCapacity: def.block || 1,
      attackTimer: 0.2,
      targetId: null,
      statuses: {},
      hitFlash: 0,
      elements: [],
      formId: "base",
      formName: "",
      formColors: [],
      traits: {},
    });
    this.state.selectedCardId = null;
    this.addEffect({ type: "spawn", x: at.x, y: at.y, color: def.color, ttl: 0.48 });
    return { type: "deploy", roleId: def.id };
  }

  tryApplyEnergy(card, x, y) {
    const unit = this.state.units
      .filter((candidate) => candidate.hp > 0)
      .sort((a, b) => Math.hypot(a.x - x, a.y - y) - Math.hypot(b.x - x, b.y - y))[0];
    if (!unit || Math.hypot(unit.x - x, unit.y - y) > Math.max(46, unit.radius + 18)) return this.rejectCard(card.id);
    const slot = this.state.deck.find((item) => item.cardId === card.id);
    if (unit.elements.length >= 2 || this.state.resource < card.cost || slot.cooldownLeft > 0) return this.rejectCard(card.id);

    this.state.resource -= card.cost;
    slot.cooldownLeft = card.cooldown;
    unit.elements.push(card.payloadId);
    this.rebuildUnitForm(unit);
    this.state.selectedCardId = null;
    this.addEffect({ type: "evolve", x: unit.x, y: unit.y, color: card.color, ttl: 0.8 });
    return { type: "energy", unitId: unit.id, element: card.payloadId, formId: unit.formId };
  }

  rebuildUnitForm(unit) {
    const def = ROLE_DEFS[unit.roleId];
    const oldMaxHp = unit.maxHp;
    let hpMultiplier = 1;
    let attackMultiplier = 1;
    let rateMultiplier = 1;
    let armorBonus = 0;
    let traits = {};
    let colors = unit.elements.map((id) => ELEMENTS[id].color);
    let formName = "";

    if (unit.elements.length === 1) {
      const element = unit.elements[0];
      formName = ELEMENTS[element].name;
      if (element === "fire") { attackMultiplier = 1.12; traits = { burn: 0.14 }; }
      if (element === "ice") { hpMultiplier = 1.1; armorBonus = 0.05; traits = { slow: 0.14 }; }
      if (element === "lightning") { rateMultiplier = 1.14; traits = {}; }
      if (element === "nature") { hpMultiplier = 1.2; traits = { regen: 0.006 }; }
      unit.formId = element;
    } else if (unit.elements.length === 2) {
      const key = sortedElements(unit.elements);
      const recipe = FORM_RECIPES[key];
      hpMultiplier = recipe.hp || 1;
      attackMultiplier = recipe.attack || 1;
      rateMultiplier = recipe.rate || 1;
      armorBonus = recipe.armor || 0;
      traits = { ...recipe.traits };
      colors = recipe.colors;
      formName = recipe.name;
      unit.formId = key;
    }

    unit.maxHp = Math.round(def.hp * hpMultiplier);
    unit.hp = Math.min(unit.maxHp, unit.hp + Math.max(0, unit.maxHp - oldMaxHp));
    unit.attack = Math.round(def.attack * attackMultiplier);
    unit.interval = def.interval / rateMultiplier;
    unit.armor = clamp(def.armor + armorBonus, 0, 0.65);
    unit.traits = traits;
    unit.formColors = colors;
    unit.formName = formName;
  }

  rejectCard(cardId) {
    const slot = this.state.deck.find((item) => item.cardId === cardId);
    if (slot) slot.flash = 0.28;
    return { type: "reject", cardId };
  }

  addEffect(effect) {
    this.state.effects.push({ ...effect, maxTtl: effect.ttl });
    if (this.state.effects.length > 80) this.state.effects.splice(0, this.state.effects.length - 80);
  }

  flashSaved() {
    this.state.message = "✓";
    this.state.messageTtl = 0.8;
  }

  serialize() {
    return JSON.stringify({
      ...this.state,
      effects: [],
      selectedCardId: null,
      savedAt: Date.now(),
    });
  }

  restore(serialized) {
    try {
      const saved = typeof serialized === "string" ? JSON.parse(serialized) : serialized;
      if (!saved || saved.schemaVersion !== 2) return false;
      const next = freshState(saved.rngSeed);
      Object.assign(next, saved);
      next.effects = [];
      next.selectedCardId = null;
      next.phase = saved.phase === "paused" ? saved.previousPhase || "ready" : saved.phase;
      next.previousPhase = next.phase;
      next.deck = CARD_DEFS.map((card) => {
        const slot = saved.deck?.find((item) => item.cardId === card.id);
        return { cardId: card.id, cooldownLeft: Math.max(0, slot?.cooldownLeft || 0), flash: 0 };
      });
      next.units = (saved.units || []).filter((unit) => ROLE_DEFS[unit.roleId]).slice(0, 12).map((unit) => {
        const cell = pointToCell(unit.x, unit.y) || { row: 0, col: 0 };
        const lane = clamp(Number.isInteger(unit.lane) ? unit.lane : cell.row, 0, BOARD.rows - 1);
        const cellCol = clamp(Number.isInteger(unit.cellCol) ? unit.cellCol : cell.col, 0, BOARD.playerCols - 1);
        const at = cellCenter(lane, cellCol);
        return {
          ...unit,
          x: at.x,
          y: at.y,
          lane,
          cellCol,
          blockCapacity: ROLE_DEFS[unit.roleId].block || 1,
        };
      });
      next.enemies = (saved.enemies || []).filter((enemy) => MONSTER_DEFS[enemy.monsterId]).map((enemy) => {
        const fallbackLane = pointToCell(enemy.x, enemy.y)?.row || 0;
        const lane = clamp(Number.isInteger(enemy.lane) ? enemy.lane : fallbackLane, 0, BOARD.rows - 1);
        return { ...enemy, lane, y: cellCenter(lane, 0).y };
      });
      this.state = next;
      return true;
    } catch {
      return false;
    }
  }

  getSnapshot() {
    return JSON.parse(this.serialize());
  }
}

const WAVE_COUNT = WAVE_SPECS.length;
const FORM_NAMES = Object.freeze(Object.fromEntries(Object.entries(FORM_RECIPES).map(([key, value]) => [key, value.name])));

Object.assign(exports, { LOGICAL_WIDTH, LOGICAL_HEIGHT, BOARD, UI, ELEMENTS, ROLE_DEFS, MONSTER_DEFS, CARD_DEFS, WAVE_POINTS, WAVE_DURATION, cellCenter, pointToCell, cardRect, TowerDefenseGame, WAVE_COUNT, FORM_NAMES });
});

__define("renderer", function (exports, __require) {
const {
  BOARD,
  CARD_DEFS,
  ELEMENTS,
  LOGICAL_HEIGHT,
  LOGICAL_WIDTH,
  UI,
  WAVE_COUNT,
  WAVE_DURATION,
  cardRect,
} = __require("core");

const TAU = Math.PI * 2;
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

function roundedRect(ctx, x, y, w, h, r) {
  const radius = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + w, y, x + w, y + h, radius);
  ctx.arcTo(x + w, y + h, x, y + h, radius);
  ctx.arcTo(x, y + h, x, y, radius);
  ctx.arcTo(x, y, x + w, y, radius);
  ctx.closePath();
}

function hexToRgba(hex, alpha) {
  const raw = String(hex || "#ffffff").replace("#", "");
  const expanded = raw.length === 3 ? raw.split("").map((char) => char + char).join("") : raw;
  const value = Number.parseInt(expanded, 16);
  if (!Number.isFinite(value)) return `rgba(255,255,255,${alpha})`;
  return `rgba(${(value >> 16) & 255}, ${(value >> 8) & 255}, ${value & 255}, ${alpha})`;
}

function drawDiamond(ctx, x, y, size, color) {
  ctx.save();
  ctx.translate(x, y);
  ctx.rotate(Math.PI / 4);
  ctx.fillStyle = color;
  roundedRect(ctx, -size / 2, -size / 2, size, size, 3);
  ctx.fill();
  ctx.restore();
}

function entityNumber(entity) {
  const value = Number.parseInt(String(entity.id || "0").replace(/\D/g, ""), 10);
  return Number.isFinite(value) ? value : 0;
}

function actorPosition(actor) {
  if (Number.isFinite(actor.x) && Number.isFinite(actor.y)) return { x: actor.x, y: actor.y };
  const col = clamp(actor.col ?? 0, 0, BOARD.cols - 1);
  const row = clamp(actor.row ?? actor.lane ?? 0, 0, BOARD.rows - 1);
  return {
    x: BOARD.x + (BOARD.width / BOARD.cols) * (col + 0.5),
    y: BOARD.y + (BOARD.height / BOARD.rows) * (row + 0.5),
  };
}

class CanvasRenderer {
  constructor(context) {
    this.ctx = context;
    this.time = 0;
  }

  draw(state, dt = 0) {
    this.time += dt;
    this.ctx.clearRect(0, 0, LOGICAL_WIDTH, LOGICAL_HEIGHT);
    this.drawBackdrop();
    this.drawBoard(state);
    this.drawActors(state);
    this.drawProjectiles(state.projectiles || []);
    this.drawEffects(state.effects || []);
    this.drawHud(state);
    this.drawCards(state);
    this.drawPhase(state);
  }

  drawBackdrop() {
    const ctx = this.ctx;
    const sky = ctx.createLinearGradient(0, 0, 0, LOGICAL_HEIGHT);
    sky.addColorStop(0, "#9bd9dc");
    sky.addColorStop(0.48, "#d8e8bc");
    sky.addColorStop(1, "#294d3d");
    ctx.fillStyle = sky;
    ctx.fillRect(0, 0, LOGICAL_WIDTH, LOGICAL_HEIGHT);
    ctx.fillStyle = "rgba(255,238,173,.72)";
    ctx.beginPath();
    ctx.arc(1018, 78, 66, 0, TAU);
    ctx.fill();

    ctx.fillStyle = "#70a277";
    ctx.beginPath();
    ctx.moveTo(0, 168);
    ctx.quadraticCurveTo(205, 54, 418, 174);
    ctx.quadraticCurveTo(650, 44, 853, 164);
    ctx.quadraticCurveTo(1080, 38, 1280, 155);
    ctx.lineTo(1280, 280);
    ctx.lineTo(0, 280);
    ctx.closePath();
    ctx.fill();

    ctx.fillStyle = "#426e59";
    for (let i = 0; i < 19; i += 1) {
      const x = 12 + i * 73 + (i % 3) * 13;
      const y = 148 + (i % 4) * 8;
      ctx.beginPath();
      ctx.moveTo(x, y + 44);
      ctx.lineTo(x + 18, y);
      ctx.lineTo(x + 36, y + 44);
      ctx.closePath();
      ctx.fill();
    }

    for (let i = 0; i < 5; i += 1) {
      const x = -16 + i * 58;
      const y = 182 + (i % 2) * 16;
      ctx.fillStyle = i % 2 ? "#e0c08a" : "#f0d49a";
      ctx.fillRect(x, y, 48, 45);
      ctx.fillStyle = i % 2 ? "#a94e43" : "#c25b48";
      ctx.beginPath();
      ctx.moveTo(x - 6, y + 2);
      ctx.lineTo(x + 24, y - 22);
      ctx.lineTo(x + 54, y + 2);
      ctx.closePath();
      ctx.fill();
    }

    const lower = ctx.createLinearGradient(0, 548, 0, LOGICAL_HEIGHT);
    lower.addColorStop(0, "rgba(27,55,46,0)");
    lower.addColorStop(0.2, "rgba(19,38,34,.88)");
    lower.addColorStop(1, "#10251f");
    ctx.fillStyle = lower;
    ctx.fillRect(0, 535, LOGICAL_WIDTH, LOGICAL_HEIGHT - 535);
  }

  drawBoard(state) {
    const ctx = this.ctx;
    const cellW = BOARD.width / BOARD.cols;
    const cellH = BOARD.height / BOARD.rows;
    const selected = CARD_DEFS.find((card) => card.id === state.selectedCardId);
    const occupied = new Set((state.units || []).map((unit) => {
      if (Number.isFinite(unit.row) && Number.isFinite(unit.col)) return `${unit.row}:${unit.col}`;
      const at = actorPosition(unit);
      return `${clamp(Math.floor((at.y - BOARD.y) / cellH), 0, BOARD.rows - 1)}:${clamp(Math.floor((at.x - BOARD.x) / cellW), 0, BOARD.cols - 1)}`;
    }));

    ctx.save();
    ctx.shadowColor = "rgba(28,39,25,.42)";
    ctx.shadowBlur = 18;
    roundedRect(ctx, BOARD.x - 8, BOARD.y - 8, BOARD.width + 16, BOARD.height + 16, 22);
    ctx.fillStyle = "#72523a";
    ctx.fill();
    ctx.shadowBlur = 0;
    roundedRect(ctx, BOARD.x, BOARD.y, BOARD.width, BOARD.height, 15);
    ctx.clip();
    ctx.fillStyle = "#78aa62";
    ctx.fillRect(BOARD.x, BOARD.y, BOARD.width, BOARD.height);

    for (let row = 0; row < BOARD.rows; row += 1) {
      const y = BOARD.y + row * cellH;
      ctx.fillStyle = row % 2 ? "#cfb274" : "#d9bf82";
      roundedRect(ctx, BOARD.x - 4, y + 6, BOARD.width + 8, cellH - 12, 18);
      ctx.fill();
      ctx.fillStyle = "rgba(255,248,209,.16)";
      ctx.fillRect(BOARD.x, y + 10, BOARD.width, 3);
      ctx.fillStyle = "rgba(80,76,46,.13)";
      for (let mark = 0; mark < 10; mark += 1) {
        const px = BOARD.x + ((mark * 137 + row * 61) % Math.max(1, BOARD.width - 24)) + 12;
        const py = y + 22 + ((mark * 29 + row * 11) % Math.max(1, cellH - 42));
        ctx.beginPath();
        ctx.ellipse(px, py, 3 + (mark % 3), 1.5, 0.3, 0, TAU);
        ctx.fill();
      }
    }

    const deployWidth = cellW * BOARD.playerCols;
    const deployTint = ctx.createLinearGradient(BOARD.x, 0, BOARD.x + deployWidth, 0);
    deployTint.addColorStop(0, "rgba(89,196,135,.18)");
    deployTint.addColorStop(1, "rgba(95,211,157,.06)");
    ctx.fillStyle = deployTint;
    ctx.fillRect(BOARD.x, BOARD.y, deployWidth, BOARD.height);
    const danger = ctx.createLinearGradient(BOARD.x + BOARD.width - cellW * 1.8, 0, BOARD.x + BOARD.width, 0);
    danger.addColorStop(0, "rgba(112,55,74,0)");
    danger.addColorStop(1, "rgba(116,42,69,.31)");
    ctx.fillStyle = danger;
    ctx.fillRect(BOARD.x + BOARD.width - cellW * 1.8, BOARD.y, cellW * 1.8, BOARD.height);

    for (let row = 0; row < BOARD.rows; row += 1) {
      for (let col = 0; col < BOARD.cols; col += 1) {
        const x = BOARD.x + col * cellW;
        const y = BOARD.y + row * cellH;
        const deployable = col < BOARD.playerCols;
        const isOccupied = occupied.has(`${row}:${col}`);
        if (selected?.type === "role" && deployable && !isOccupied) {
          const pulse = 0.13 + Math.sin(this.time * 5 + row * 0.7 + col) * 0.035;
          ctx.fillStyle = hexToRgba(selected.color, pulse);
          roundedRect(ctx, x + 5, y + 7, cellW - 10, cellH - 14, 12);
          ctx.fill();
        }
        ctx.strokeStyle = deployable ? "rgba(245,255,226,.4)" : "rgba(255,245,213,.18)";
        ctx.lineWidth = deployable ? 1.5 : 1;
        roundedRect(ctx, x + 4.5, y + 6.5, cellW - 9, cellH - 13, 10);
        ctx.stroke();
        if (isOccupied && selected?.type === "role") {
          ctx.fillStyle = "rgba(46,55,42,.16)";
          roundedRect(ctx, x + 6, y + 8, cellW - 12, cellH - 16, 10);
          ctx.fill();
        }
      }
    }

    const fenceX = BOARD.x + deployWidth;
    ctx.strokeStyle = "rgba(85,58,35,.58)";
    ctx.lineWidth = 4;
    ctx.beginPath();
    ctx.moveTo(fenceX, BOARD.y);
    ctx.lineTo(fenceX, BOARD.y + BOARD.height);
    ctx.stroke();
    ctx.fillStyle = "#a77548";
    for (let row = 0; row <= BOARD.rows; row += 1) {
      const y = BOARD.y + row * cellH;
      ctx.fillRect(fenceX - 6, y - 8, 12, 16);
    }

    ctx.fillStyle = "rgba(107,52,68,.42)";
    for (let row = 0; row < BOARD.rows; row += 1) {
      const y = BOARD.y + cellH * (row + 0.5);
      ctx.beginPath();
      ctx.moveTo(BOARD.x + BOARD.width - 17, y);
      ctx.lineTo(BOARD.x + BOARD.width - 3, y - 9);
      ctx.lineTo(BOARD.x + BOARD.width - 3, y + 9);
      ctx.closePath();
      ctx.fill();
    }
    ctx.restore();
    this.drawTownGate(state);
    this.drawMonsterEntry();
  }

  drawTownGate(state) {
    const ctx = this.ctx;
    const x = BOARD.x - 15;
    const top = BOARD.y - 12;
    const h = BOARD.height + 24;
    ctx.save();
    ctx.shadowColor = "rgba(18,25,18,.4)";
    ctx.shadowBlur = 10;
    ctx.fillStyle = "#9a7654";
    roundedRect(ctx, x - 27, top, 36, h, 10);
    ctx.fill();
    ctx.shadowBlur = 0;
    ctx.fillStyle = "#c7a36e";
    for (let y = top + 8, index = 0; y < top + h - 7; y += 25, index += 1) {
      ctx.fillRect(x - 23 + (index % 2) * 4, y, 28, 17);
    }
    ctx.fillStyle = "#69472f";
    for (let row = 0; row < BOARD.rows; row += 1) {
      const cy = BOARD.y + (BOARD.height / BOARD.rows) * (row + 0.5);
      roundedRect(ctx, x - 10, cy - 23, 22, 46, 6);
      ctx.fill();
      ctx.strokeStyle = "#d6b779";
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.moveTo(x - 7, cy - 12);
      ctx.lineTo(x + 9, cy - 3);
      ctx.moveTo(x - 7, cy + 8);
      ctx.lineTo(x + 9, cy + 17);
      ctx.stroke();
    }
    const hp = Math.max(0, state.gateHp || 0);
    const maxHp = Math.max(1, state.gateMaxHp || 3);
    for (let i = 0; i < maxHp; i += 1) {
      const cy = BOARD.y + BOARD.height / 2 + (i - (maxHp - 1) / 2) * 27;
      ctx.globalAlpha = i < hp ? 1 : 0.2;
      ctx.fillStyle = i < hp ? "#72dfac" : "#32433b";
      ctx.beginPath();
      ctx.moveTo(x - 35, cy - 9);
      ctx.lineTo(x - 25, cy - 5);
      ctx.lineTo(x - 27, cy + 7);
      ctx.lineTo(x - 35, cy + 13);
      ctx.lineTo(x - 43, cy + 7);
      ctx.lineTo(x - 45, cy - 5);
      ctx.closePath();
      ctx.fill();
    }
    ctx.restore();
  }

  drawMonsterEntry() {
    const ctx = this.ctx;
    const x = BOARD.x + BOARD.width + 3;
    const y = BOARD.y + BOARD.height / 2;
    const pulse = 0.82 + Math.sin(this.time * 2.8) * 0.08;
    ctx.save();
    ctx.translate(x, y);
    ctx.scale(pulse, 1);
    ctx.strokeStyle = "rgba(101,52,91,.72)";
    ctx.lineWidth = 9;
    ctx.beginPath();
    ctx.ellipse(0, 0, 18, BOARD.height * 0.45, 0, 0, TAU);
    ctx.stroke();
    ctx.strokeStyle = "rgba(232,104,143,.46)";
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.ellipse(0, 0, 10, BOARD.height * 0.42, 0, 0, TAU);
    ctx.stroke();
    ctx.restore();
  }

  drawActors(state) {
    const selected = CARD_DEFS.find((card) => card.id === state.selectedCardId);
    const actors = [
      ...(state.units || []).map((actor) => ({ actor, side: "ally", position: actorPosition(actor) })),
      ...(state.enemies || []).map((actor) => ({ actor, side: "enemy", position: actorPosition(actor) })),
    ].sort((a, b) => a.position.y - b.position.y || a.position.x - b.position.x);
    for (const entry of actors) {
      if (entry.side === "ally") this.drawAlly(entry.actor, entry.position, selected);
      else this.drawMonster(entry.actor, entry.position);
    }
  }

  drawAlly(unit, position, selectedCard) {
    const ctx = this.ctx;
    const radius = unit.radius || 21;
    const x = position.x;
    const y = position.y + Math.sin(this.time * 3.4 + entityNumber(unit)) * 1.6;
    ctx.save();
    ctx.translate(x, y);
    if (selectedCard?.type === "energy" && (unit.elements?.length || 0) < 2) {
      ctx.strokeStyle = hexToRgba(selectedCard.color, 0.62 + Math.sin(this.time * 6) * 0.14);
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.arc(0, 0, radius + 13, 0, TAU);
      ctx.stroke();
      ctx.fillStyle = hexToRgba(selectedCard.color, 0.1);
      ctx.beginPath();
      ctx.arc(0, 0, radius + 10, 0, TAU);
      ctx.fill();
    }
    (unit.formColors || []).forEach((color, index) => {
      ctx.strokeStyle = hexToRgba(color, 0.62);
      ctx.lineWidth = 3;
      ctx.beginPath();
      const start = this.time * (index ? -1.3 : 1.5) + index * Math.PI;
      ctx.arc(0, 0, radius + 6 + index * 4, start, start + Math.PI * 1.18);
      ctx.stroke();
    });
    ctx.fillStyle = "rgba(38,42,28,.27)";
    ctx.beginPath();
    ctx.ellipse(0, radius * 0.86, radius, radius * 0.32, 0, 0, TAU);
    ctx.fill();

    const hitColor = unit.hitFlash > 0 ? "#ffffff" : unit.color;
    ctx.fillStyle = "#403443";
    ctx.beginPath();
    ctx.arc(0, -radius * 0.42, radius * 0.65, Math.PI, TAU);
    ctx.lineTo(radius * 0.58, radius * 0.2);
    ctx.lineTo(-radius * 0.58, radius * 0.2);
    ctx.closePath();
    ctx.fill();
    ctx.fillStyle = unit.hitFlash > 0 ? "#ffffff" : "#ffe1ca";
    ctx.beginPath();
    ctx.arc(0, -radius * 0.38, radius * 0.49, 0, TAU);
    ctx.fill();
    ctx.fillStyle = hitColor;
    ctx.beginPath();
    ctx.moveTo(-radius * 0.67, radius * 0.84);
    ctx.quadraticCurveTo(-radius * 0.45, radius * 0.04, 0, -radius * 0.02);
    ctx.quadraticCurveTo(radius * 0.45, radius * 0.04, radius * 0.67, radius * 0.84);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = "rgba(255,255,255,.72)";
    ctx.lineWidth = 2;
    ctx.stroke();
    ctx.fillStyle = "#49363c";
    ctx.beginPath();
    ctx.arc(-radius * 0.18, -radius * 0.4, 1.4, 0, TAU);
    ctx.arc(radius * 0.18, -radius * 0.4, 1.4, 0, TAU);
    ctx.fill();
    ctx.fillStyle = "rgba(27,33,35,.72)";
    ctx.beginPath();
    ctx.arc(0, radius * 0.38, radius * 0.29, 0, TAU);
    ctx.fill();
    ctx.fillStyle = "#ffffff";
    ctx.font = `800 ${Math.max(11, radius * 0.58)}px system-ui, sans-serif`;
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText(unit.glyph || "•", 0, radius * 0.4);
    ctx.restore();
    this.drawHealth(unit, x, position.y, "ally");
    this.drawElements(unit, x, position.y);
  }

  drawMonster(enemy, position) {
    const ctx = this.ctx;
    const radius = enemy.radius || 20;
    const x = position.x;
    const y = position.y + Math.sin(this.time * 3 + entityNumber(enemy)) * 2;
    ctx.save();
    ctx.translate(x, y);
    ctx.fillStyle = "rgba(42,31,37,.28)";
    ctx.beginPath();
    ctx.ellipse(0, radius * 0.9, radius, radius * 0.34, 0, 0, TAU);
    ctx.fill();
    ctx.fillStyle = enemy.hitFlash > 0 ? "#ffffff" : enemy.color;
    ctx.strokeStyle = "rgba(72,38,59,.55)";
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(-radius, radius * 0.38);
    ctx.quadraticCurveTo(-radius * 1.03, -radius * 0.58, -radius * 0.44, -radius * 0.83);
    ctx.quadraticCurveTo(0, -radius * 1.12, radius * 0.44, -radius * 0.83);
    ctx.quadraticCurveTo(radius * 1.03, -radius * 0.58, radius, radius * 0.38);
    ctx.quadraticCurveTo(radius * 0.62, radius, 0, radius * 0.82);
    ctx.quadraticCurveTo(-radius * 0.62, radius, -radius, radius * 0.38);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
    ctx.fillStyle = enemy.color;
    ctx.beginPath();
    ctx.moveTo(-radius * 0.73, -radius * 0.61);
    ctx.lineTo(-radius * 0.31, -radius * 1.2);
    ctx.lineTo(-radius * 0.06, -radius * 0.69);
    ctx.moveTo(radius * 0.73, -radius * 0.61);
    ctx.lineTo(radius * 0.31, -radius * 1.2);
    ctx.lineTo(radius * 0.06, -radius * 0.69);
    ctx.fill();
    ctx.fillStyle = "#26192a";
    ctx.beginPath();
    ctx.ellipse(-radius * 0.3, -radius * 0.15, 3.2, 4.2, -0.2, 0, TAU);
    ctx.ellipse(radius * 0.3, -radius * 0.15, 3.2, 4.2, 0.2, 0, TAU);
    ctx.fill();
    ctx.strokeStyle = "#4a263a";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(0, radius * 0.21, radius * 0.22, 0.15, Math.PI - 0.15);
    ctx.stroke();
    ctx.restore();
    this.drawHealth(enemy, x, position.y, "enemy");
  }

  drawHealth(actor, x, y, side) {
    const ctx = this.ctx;
    const radius = actor.radius || 20;
    const width = Math.max(34, radius * 2.15);
    const left = x - width / 2;
    const top = y - radius - 14;
    ctx.fillStyle = "rgba(35,31,25,.62)";
    roundedRect(ctx, left, top, width, 6, 3);
    ctx.fill();
    const ratio = clamp((actor.hp || 0) / Math.max(1, actor.maxHp || 1), 0, 1);
    if (ratio > 0) {
      ctx.fillStyle = side === "ally" ? "#65d69a" : "#ee687b";
      roundedRect(ctx, left + 1, top + 1, (width - 2) * ratio, 4, 2);
      ctx.fill();
    }
  }

  drawElements(unit, x, y) {
    if (!unit.elements?.length) return;
    const radius = unit.radius || 20;
    unit.elements.forEach((element, index) => {
      const definition = ELEMENTS[element];
      if (!definition) return;
      const px = x + (index - (unit.elements.length - 1) / 2) * 14;
      const py = y - radius - 24;
      this.ctx.fillStyle = "rgba(255,255,255,.72)";
      this.ctx.beginPath();
      this.ctx.arc(px, py, 6.5, 0, TAU);
      this.ctx.fill();
      drawDiamond(this.ctx, px, py, 8, definition.color);
    });
  }

  drawProjectiles(projectiles) {
    const ctx = this.ctx;
    for (const projectile of projectiles) {
      if (!Number.isFinite(projectile.x) || !Number.isFinite(projectile.y)) continue;
      const color = projectile.color || projectile.formColor || "#fff2a2";
      const vx = projectile.vx || 0;
      const vy = projectile.vy || 0;
      const length = Math.hypot(vx, vy) || 1;
      const trail = Math.min(22, length * 0.08 + 8);
      ctx.save();
      ctx.strokeStyle = hexToRgba(color, 0.38);
      ctx.lineWidth = 4;
      ctx.beginPath();
      ctx.moveTo(projectile.x, projectile.y);
      ctx.lineTo(projectile.x - (vx / length) * trail, projectile.y - (vy / length) * trail);
      ctx.stroke();
      ctx.shadowColor = color;
      ctx.shadowBlur = 9;
      ctx.fillStyle = color;
      ctx.beginPath();
      ctx.arc(projectile.x, projectile.y, projectile.radius || 4, 0, TAU);
      ctx.fill();
      ctx.restore();
    }
  }

  drawEffects(effects) {
    const ctx = this.ctx;
    for (const effect of effects) {
      const progress = 1 - effect.ttl / effect.maxTtl;
      const p = Number.isFinite(progress) ? clamp(progress, 0, 1) : 0;
      const alpha = clamp(effect.ttl / Math.min(effect.maxTtl || 0.35, 0.35), 0, 1);
      ctx.save();
      ctx.globalAlpha = alpha;
      if (effect.type === "shot") {
        const eased = 1 - (1 - p) * (1 - p);
        const x = effect.fromX + (effect.x - effect.fromX) * eased;
        const y = effect.fromY + (effect.y - effect.fromY) * eased - Math.sin(eased * Math.PI) * 12;
        ctx.strokeStyle = hexToRgba(effect.color || "#fff0a0", 0.48);
        ctx.lineWidth = 3;
        ctx.beginPath();
        ctx.moveTo(effect.fromX + (x - effect.fromX) * 0.75, effect.fromY + (y - effect.fromY) * 0.75);
        ctx.lineTo(x, y);
        ctx.stroke();
        ctx.fillStyle = effect.color || "#fff0a0";
        ctx.beginPath();
        ctx.arc(x, y, 4.5, 0, TAU);
        ctx.fill();
      } else if (["chain", "heal"].includes(effect.type)) {
        ctx.strokeStyle = effect.type === "chain" ? "#ffe56f" : "#7cf1ae";
        ctx.lineWidth = effect.type === "chain" ? 3 : 4;
        ctx.beginPath();
        ctx.moveTo(effect.fromX, effect.fromY);
        if (effect.type === "chain") ctx.lineTo((effect.fromX + effect.x) / 2 + Math.sin(p * 22) * 8, (effect.fromY + effect.y) / 2 + Math.cos(p * 18) * 8);
        ctx.lineTo(effect.x, effect.y);
        ctx.stroke();
      } else if (["spawn", "evolve", "burst", "gate", "down"].includes(effect.type)) {
        const maxRadius = effect.type === "burst" ? effect.radius : effect.type === "evolve" ? 56 : 38;
        ctx.strokeStyle = effect.color || "#fff";
        ctx.lineWidth = effect.type === "evolve" ? 5 : 3;
        ctx.beginPath();
        ctx.arc(effect.x, effect.y, 7 + maxRadius * p, 0, TAU);
        ctx.stroke();
      } else if (effect.type === "slash") {
        ctx.strokeStyle = effect.color || "#fff";
        ctx.lineWidth = 4;
        ctx.beginPath();
        ctx.arc(effect.x, effect.y, 20, -0.8 + p, 1.2 + p);
        ctx.stroke();
      } else if (effect.type === "number") {
        ctx.fillStyle = effect.color;
        ctx.font = "800 14px system-ui, sans-serif";
        ctx.textAlign = "center";
        ctx.fillText(String(effect.value), effect.x, effect.y - p * 24);
      } else if (effect.type === "banner") {
        ctx.fillStyle = "#fff9dc";
        ctx.font = "900 32px system-ui, sans-serif";
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillText(effect.text, LOGICAL_WIDTH / 2, 73 + Math.sin(p * Math.PI) * 5);
      }
      ctx.restore();
    }
  }

  drawHud(state) {
    const ctx = this.ctx;
    ctx.save();
    ctx.fillStyle = "rgba(38,63,50,.88)";
    ctx.strokeStyle = "rgba(247,226,166,.58)";
    ctx.lineWidth = 2;
    roundedRect(ctx, 20, 12, 188, 50, 15);
    ctx.fill();
    ctx.stroke();
    ctx.fillStyle = "#fff4cc";
    ctx.font = "900 23px system-ui, sans-serif";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText("小镇别慌", 114, 37);
    ctx.fillStyle = "rgba(52,70,48,.88)";
    roundedRect(ctx, 220, 13, 124, 48, 15);
    ctx.fill();
    drawDiamond(ctx, 246, 37, 18, "#f4ce63");
    ctx.fillStyle = "#fff1ad";
    ctx.font = "900 22px ui-monospace, monospace";
    ctx.textAlign = "left";
    ctx.fillText(String(state.resource), 265, 38);

    const waveNumber = state.wave?.index < 0 ? 1 : state.wave.index + 1;
    const seconds = state.phase === "ready" ? WAVE_DURATION : Math.max(0, Math.ceil(WAVE_DURATION - (state.wave?.elapsed || 0)));
    ctx.fillStyle = "rgba(48,59,46,.86)";
    roundedRect(ctx, 513, 13, 254, 48, 16);
    ctx.fill();
    ctx.fillStyle = "#f7edca";
    ctx.font = "900 18px ui-monospace, monospace";
    ctx.textAlign = "center";
    ctx.fillText(`${waveNumber}/${WAVE_COUNT}`, 574, 38);
    ctx.fillStyle = seconds <= 8 && state.phase === "playing" ? "#ff7a78" : "#ffffff";
    ctx.font = "900 22px ui-monospace, monospace";
    ctx.fillText(String(seconds).padStart(2, "0"), 696, 38);
    UI.controls.forEach((button) => this.drawControl(button, state));
    ctx.restore();
  }

  drawControl(button, state) {
    const ctx = this.ctx;
    const active = (button.id === "pause" && state.phase === "paused") || (button.id === "start" && state.phase === "ready");
    ctx.fillStyle = active ? "rgba(104,195,135,.92)" : "rgba(48,63,50,.9)";
    ctx.strokeStyle = active ? "#d9f0a8" : "rgba(242,224,171,.42)";
    ctx.lineWidth = 1.7;
    roundedRect(ctx, button.x, button.y, button.w, button.h, 12);
    ctx.fill();
    ctx.stroke();
    const cx = button.x + button.w / 2;
    const cy = button.y + button.h / 2;
    ctx.fillStyle = active ? "#fffbd8" : "#eee7ce";
    ctx.strokeStyle = ctx.fillStyle;
    ctx.lineWidth = 3;
    if (button.id === "start" || (button.id === "pause" && state.phase === "paused")) {
      ctx.beginPath();
      ctx.moveTo(cx - 6, cy - 9);
      ctx.lineTo(cx + 9, cy);
      ctx.lineTo(cx - 6, cy + 9);
      ctx.closePath();
      ctx.fill();
    } else if (button.id === "pause") {
      ctx.fillRect(cx - 8, cy - 9, 5, 18);
      ctx.fillRect(cx + 3, cy - 9, 5, 18);
    } else if (button.id === "restart") {
      ctx.beginPath();
      ctx.arc(cx, cy, 9, -0.75, Math.PI * 1.55);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(cx - 9, cy - 8);
      ctx.lineTo(cx - 10, cy + 1);
      ctx.lineTo(cx - 2, cy - 3);
      ctx.fill();
    } else if (button.id === "save") {
      ctx.strokeRect(cx - 9, cy - 9, 18, 18);
      ctx.fillRect(cx - 5, cy - 9, 10, 6);
      ctx.beginPath();
      ctx.arc(cx, cy + 4, 3, 0, TAU);
      ctx.fill();
    }
  }

  drawCards(state) {
    const ctx = this.ctx;
    if (!CARD_DEFS.length) return;
    const first = cardRect(0);
    const last = cardRect(CARD_DEFS.length - 1);
    ctx.save();
    ctx.fillStyle = "rgba(38,58,45,.9)";
    ctx.strokeStyle = "rgba(234,214,153,.46)";
    ctx.lineWidth = 2;
    roundedRect(ctx, first.x - 10, first.y - 10, last.x + last.w - first.x + 20, first.h + 18, 18);
    ctx.fill();
    ctx.stroke();
    CARD_DEFS.forEach((card, index) => {
      const rect = cardRect(index);
      const slot = state.deck?.[index] || { cooldownLeft: 0, flash: 0 };
      const selected = state.selectedCardId === card.id;
      const affordable = state.resource >= card.cost;
      const ready = slot.cooldownLeft <= 0;
      ctx.save();
      if (slot.flash > 0) ctx.translate(Math.sin(slot.flash * 85) * 4, 0);
      if (!affordable || !ready) ctx.globalAlpha = 0.72;
      ctx.shadowColor = selected ? card.color : "rgba(0,0,0,.28)";
      ctx.shadowBlur = selected ? 17 : 5;
      ctx.fillStyle = selected ? hexToRgba(card.color, 0.35) : "#263c32";
      ctx.strokeStyle = selected ? card.color : "rgba(239,223,179,.42)";
      ctx.lineWidth = selected ? 3 : 1.5;
      roundedRect(ctx, rect.x, rect.y, rect.w, rect.h, 14);
      ctx.fill();
      ctx.stroke();
      ctx.shadowBlur = 0;
      ctx.fillStyle = "rgba(250,242,208,.08)";
      roundedRect(ctx, rect.x + 6, rect.y + 6, rect.w - 12, 66, 10);
      ctx.fill();

      if (card.type === "energy") {
        ctx.shadowColor = card.color;
        ctx.shadowBlur = selected ? 13 : 5;
        drawDiamond(ctx, rect.x + rect.w / 2, rect.y + 39, 38, card.color);
      } else {
        ctx.fillStyle = "#443743";
        ctx.beginPath();
        ctx.arc(rect.x + rect.w / 2, rect.y + 30, 20, Math.PI, TAU);
        ctx.lineTo(rect.x + rect.w / 2 + 18, rect.y + 52);
        ctx.lineTo(rect.x + rect.w / 2 - 18, rect.y + 52);
        ctx.closePath();
        ctx.fill();
        ctx.fillStyle = "#ffe1ca";
        ctx.beginPath();
        ctx.arc(rect.x + rect.w / 2, rect.y + 30, 13, 0, TAU);
        ctx.fill();
        ctx.fillStyle = card.color;
        ctx.beginPath();
        ctx.moveTo(rect.x + rect.w / 2 - 22, rect.y + 66);
        ctx.lineTo(rect.x + rect.w / 2 - 12, rect.y + 42);
        ctx.lineTo(rect.x + rect.w / 2 + 12, rect.y + 42);
        ctx.lineTo(rect.x + rect.w / 2 + 22, rect.y + 66);
        ctx.closePath();
        ctx.fill();
      }
      ctx.shadowBlur = 0;
      ctx.fillStyle = "#ffffff";
      ctx.font = "900 18px system-ui, sans-serif";
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      ctx.fillText(card.glyph, rect.x + rect.w / 2, rect.y + 45);
      drawDiamond(ctx, rect.x + 18, rect.y + rect.h - 17, 12, affordable ? "#f1c95c" : "#716e62");
      ctx.fillStyle = affordable ? "#fff0a4" : "#aaa799";
      ctx.font = "900 14px ui-monospace, monospace";
      ctx.textAlign = "left";
      ctx.fillText(String(card.cost), rect.x + 29, rect.y + rect.h - 16);
      if (selected) {
        ctx.fillStyle = card.color;
        ctx.beginPath();
        ctx.moveTo(rect.x + rect.w / 2 - 7, rect.y - 7);
        ctx.lineTo(rect.x + rect.w / 2 + 7, rect.y - 7);
        ctx.lineTo(rect.x + rect.w / 2, rect.y + 1);
        ctx.closePath();
        ctx.fill();
      }
      if (!ready) {
        const ratio = clamp(slot.cooldownLeft / Math.max(0.01, card.cooldown), 0, 1);
        ctx.fillStyle = "rgba(25,27,24,.73)";
        roundedRect(ctx, rect.x, rect.y, rect.w, rect.h * ratio, 14);
        ctx.fill();
        ctx.fillStyle = "#fff9e7";
        ctx.font = "900 17px ui-monospace, monospace";
        ctx.textAlign = "center";
        ctx.fillText(slot.cooldownLeft.toFixed(1), rect.x + rect.w / 2, rect.y + 50);
      }
      ctx.restore();
    });
    ctx.restore();
  }

  drawPhase(state) {
    let title = "";
    if (state.phase === "ready") title = "▶ 开始";
    if (state.phase === "paused") title = "暂停";
    if (state.phase === "intermission") title = `${Math.max(1, Math.ceil(state.wave?.intermission || 0))}`;
    if (state.phase === "victory") title = "守住了";
    if (state.phase === "defeat") title = "失守";
    if (title) {
      const ctx = this.ctx;
      ctx.save();
      ctx.fillStyle = "rgba(42,56,43,.76)";
      ctx.strokeStyle = "rgba(250,229,166,.5)";
      ctx.lineWidth = 2;
      roundedRect(ctx, LOGICAL_WIDTH / 2 - 79, 286, 158, 56, 18);
      ctx.fill();
      ctx.stroke();
      ctx.fillStyle = "#fff6d8";
      ctx.font = "900 28px system-ui, sans-serif";
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      ctx.fillText(title, LOGICAL_WIDTH / 2, 315);
      ctx.restore();
    }
    if (state.message) this.drawToast(state.message);
  }

  drawToast(text) {
    const ctx = this.ctx;
    ctx.save();
    ctx.font = "900 18px system-ui, sans-serif";
    const width = clamp(ctx.measureText(String(text)).width + 34, 58, 190);
    const x = LOGICAL_WIDTH / 2 - width / 2;
    ctx.fillStyle = "rgba(38,58,45,.92)";
    ctx.strokeStyle = "rgba(226,238,173,.55)";
    ctx.lineWidth = 1.5;
    roundedRect(ctx, x, 550, width, 34, 17);
    ctx.fill();
    ctx.stroke();
    ctx.fillStyle = "#b9f1c8";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText(String(text), LOGICAL_WIDTH / 2, 567);
    ctx.restore();
  }
}

Object.assign(exports, { CanvasRenderer });
});

__define("platform-wechat", function (exports, __require) {
/**
 * WeChat Mini Game implementation of the same small platform surface used by
 * BrowserPlatform. Battle rules and rendering stay platform agnostic.
 */
class WechatPlatform {
  constructor(canvas, logicalWidth, logicalHeight) {
    this.canvas = canvas;
    this.logicalWidth = logicalWidth;
    this.logicalHeight = logicalHeight;
    this.context = canvas.getContext("2d", { alpha: false });
    this.pointerHandler = null;
    this.visibilityHandler = null;
    this.scale = 1;
    this.offsetX = 0;
    this.offsetY = 0;

    this.handleTouch = this.onTouch.bind(this);
    this.handleHide = this.onHide.bind(this);
    this.handleResize = this.resize.bind(this);

    wx.onTouchStart(this.handleTouch);
    wx.onHide(this.handleHide);
    if (typeof wx.onWindowResize === "function") wx.onWindowResize(this.handleResize);
    this.resize();
  }

  getWindowInfo() {
    if (typeof wx.getWindowInfo === "function") return wx.getWindowInfo();
    return wx.getSystemInfoSync();
  }

  resize() {
    const info = this.getWindowInfo();
    const windowWidth = Math.max(1, info.windowWidth || info.screenWidth || this.logicalWidth);
    const windowHeight = Math.max(1, info.windowHeight || info.screenHeight || this.logicalHeight);
    const dpr = Math.min(info.pixelRatio || info.devicePixelRatio || 1, 2);

    this.scale = Math.min(windowWidth / this.logicalWidth, windowHeight / this.logicalHeight);
    this.offsetX = (windowWidth - this.logicalWidth * this.scale) / 2;
    this.offsetY = (windowHeight - this.logicalHeight * this.scale) / 2;

    this.canvas.width = Math.round(windowWidth * dpr);
    this.canvas.height = Math.round(windowHeight * dpr);
    this.context.setTransform(
      dpr * this.scale,
      0,
      0,
      dpr * this.scale,
      dpr * this.offsetX,
      dpr * this.offsetY,
    );
    this.context.imageSmoothingEnabled = true;
  }

  onTouch(event) {
    const touch = event.changedTouches?.[0] || event.touches?.[0];
    if (!touch) return;
    const x = (touch.clientX - this.offsetX) / this.scale;
    const y = (touch.clientY - this.offsetY) / this.scale;
    this.pointerHandler?.({ x, y, pointerType: "touch" });
  }

  onHide() {
    this.visibilityHandler?.();
  }

  setPointerHandler(handler) {
    this.pointerHandler = handler;
  }

  setKeyHandler() {}

  setVisibilityHandler(handler) {
    this.visibilityHandler = handler;
  }

  now() {
    return Date.now();
  }

  requestFrame(callback) {
    const wrapped = (timestamp) => callback(Number.isFinite(timestamp) ? timestamp : this.now());
    if (typeof this.canvas.requestAnimationFrame === "function") {
      return this.canvas.requestAnimationFrame(wrapped);
    }
    if (typeof requestAnimationFrame === "function") return requestAnimationFrame(wrapped);
    return setTimeout(() => wrapped(this.now()), 16);
  }

  load(key) {
    try {
      return wx.getStorageSync(key) || null;
    } catch {
      return null;
    }
  }

  save(key, value) {
    try {
      wx.setStorageSync(key, value);
      return true;
    } catch {
      return false;
    }
  }

  remove(key) {
    try {
      wx.removeStorageSync(key);
      return true;
    } catch {
      return false;
    }
  }
}


Object.assign(exports, { WechatPlatform });
});

__define("main-wechat", function (exports, __require) {
const { TowerDefenseGame, LOGICAL_HEIGHT, LOGICAL_WIDTH } = __require("core");
const { WechatPlatform } = __require("platform-wechat");
const { CanvasRenderer } = __require("renderer");

const SAVE_KEY = "xiaozhen-biehuang-tower-defense-v2";
const FIXED_STEP = 1 / 60;

const canvas = wx.createCanvas();
const platform = new WechatPlatform(canvas, LOGICAL_WIDTH, LOGICAL_HEIGHT);
const game = new TowerDefenseGame();
const renderer = new CanvasRenderer(platform.context);

const saved = platform.load(SAVE_KEY);
if (saved) game.restore(saved);

function save() {
  if (platform.save(SAVE_KEY, game.serialize())) game.flashSaved();
}

function handleAction(action) {
  if (!action) return;
  if (action.type === "save") save();
  if (action.type === "restart") {
    platform.remove(SAVE_KEY);
    save();
  }
}

platform.setPointerHandler(({ x, y }) => handleAction(game.handleTap(x, y)));
platform.setVisibilityHandler(() => {
  game.pauseForVisibility();
  save();
});

let previous = platform.now();
let accumulator = 0;
let autosaveClock = 0;

function frame(timestamp) {
  const frameDelta = Math.min(0.1, Math.max(0, (timestamp - previous) / 1000));
  previous = timestamp;
  accumulator += frameDelta;

  while (accumulator >= FIXED_STEP) {
    game.update(FIXED_STEP);
    accumulator -= FIXED_STEP;
    autosaveClock += FIXED_STEP;
    if (autosaveClock >= 10) {
      autosaveClock = 0;
      platform.save(SAVE_KEY, game.serialize());
    }
  }

  renderer.draw(game.state, frameDelta);
  platform.requestFrame(frame);
}

renderer.draw(game.state, 0);
platform.requestFrame(frame);

});

__require("main-wechat");
